#!/bin/bash
#ls env/bin/activate

pythonver=$(python -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [ "$pythonver" -lt "38" ] && [ -f env/bin/activate ]; then 
    . env/bin/activate
fi

pythonver=$(python -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [ "$pythonver" -lt "38" ]; then
    echo "This script requires python 3.8 or greater, you have $pythonver"
    exit 1
fi

util_path=$(dirname $0)/../plugin/util.py
# ../plugin/util.py exists go into installation mode
if [ -f $util_path ]; then 
    echo "The file $(realpath $util_path) exist";
    # cd -> mbplugin/standalone
    cd $(dirname $0)
    cp $(basename $0) ../..
    # cd return to proj root (mbstandalone)
    cd ../.. 
    chmod +r $(basename $0)
    if [ ! -f phones.ini ]; then cp mbplugin/standalone/phones.ini . ; fi
    if [ ! -f mbplugin.ini ]; then python mbplugin/plugin/util.py standalone-init ; fi
    python mbplugin/plugin/util.py install-chromium
    #python mbplugin/plugin/util.py check-import
    python mbplugin/plugin/util.py check-ini
    python mbplugin/plugin/util.py clear-browser-cache
    ##python mbplugin/plugin/util.py check-playwright
    exit 0
fi

cd $(dirname $0)
python mbplugin/plugin/util.py $*

if [[ "$VIRTUAL_ENV" != "" ]]
then
  deactivate
fi

